/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:7ba6a5a4-aeb6-4c81-ac74-a6f022ea966f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_J44wX7kV8",
    "aws_user_pools_web_client_id": "4uv0dq1i2i7s4ikd7gjuku4h9r",
    "oauth": {}
};


export default awsmobile;
